### ISSUE TITLE
export TRAVIS_WORKER_GCE_PREEMPTIBLE=false ends up true

### ISSUE THREAD

**Issue by solarce** [travis-ci/worker#152]
`export TRAVIS_WORKER_GCE_PREEMPTIBLE=false` ends up `true` right now, https://github.com/travis-ci/worker/commit/22bac6a85722152d43c9a8ccb33f2f14f33b4547#diff-29702cc9152fdbf12f38885dc8173c21R70

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
totes just ran into this one too, fixing.
