### ISSUE TITLE
Travis Enterprise Worker doesn't like ZFS, but works great with BTRFS

### ISSUE THREAD

**Issue by detro** [travis-ci/worker#172]
I have successfully managed to setup Travis Worker with Docker 1.10.3.

First, in a gist:
- stopped `travis-worker` and `docker`
- followed the [official docker install/update instructions for Ubuntu](https://docs.docker.com/engine/installation/linux/ubuntulinux/#update-your-apt-sources) 
- set Docker up to use a [Btrfs volume](https://docs.docker.com/engine/userguide/storagedriver/btrfs-driver/)
- changed the `/etc/default/travis-worker` to point at `tcp://localhost:2375` to communicate with Docker
- started `docker` and `travis-worker`

This gave me a working Docker+Btrfs Travis Worker. All good.

Then I did the same for ZFS ([Docker ZFS setup](https://docs.docker.com/engine/userguide/storagedriver/zfs-driver/)) but that never worked.
While I was able to launch Travis containers on ZFS, [as explained in the official Travis CI docs](https://enterprise.travis-ci.com/docs#starting-a-build-container-on-the-worker-host-%28debug-containers%29), Travis Worker never managed to pick up job and entered in an ever retrying state.

By looking at `/var/log/upstart/travis-worker.log` I could see errors of the Worker trying to connect to `127.17.0.2:22` (what I presume is the SSH connection through which the Worker hands off work to the Container `build.sh`).
I have dug around the code in this repo a bit to see where that code was generated, but I couldn't find anywhere a log line resembling `travis worker dial tcp 172.17.0.2:22: getsockopt: connection refused`.

I hope this can be helpful for future version of Travis that, I hope, can support the awesome ZFS: a filesystem that is WAY more stable and reliable than BTRFS or AUFS.

**Comment by meatballhat** [comment]
@detro Are you able to try this with `TRAVIS_WORKER_DOCKER_NATIVE=true`, which will result in the docker backend using `exec` instead of ssh?

**Comment by meatballhat** [comment]
@detro Please holler if you believe this should be reopened :heart:
