### ISSUE TITLE
py.test not returning after passing all tests in container

### ISSUE THREAD

**Issue by brackendawson** [travis-ci/worker#175]
I'm having a seemingly random problem.

I made a commit which on my machine passes, but on travis passed and then never exited: https://travis-ci.org/somakeit/door-controller2/builds/130965876

I then worked on a branch changing the way the recent tests I had added ran until travis worked again, I made a PR back to master and all was passing: https://travis-ci.org/somakeit/door-controller2/builds/132084380

I merged the PR into master and it failed again: https://travis-ci.org/somakeit/door-controller2/builds/132085414 :'-(

Is there a way I can find out what's randmly keeping py.test from returning?

**Comment by BanzaiMan** [comment]
Is this an issue related to worker? General Travis CI issues should go to https://github.com/travis-ci/travis-ci/issues.

**Comment by brackendawson** [comment]
OK, will move there.
