### ISSUE TITLE
travis-build appears to be botching envvar decoding

### ISSUE THREAD

**Issue by StoneCypher** [travis-ci/worker#180]
Sorry, I'm pretty sure this belongs in [travis-build](https://github.com/travis-ci/travis-build), but you have issues turned off over there

On allowing the ruby commandline to add encrypted envvars, the export step in decryption is:

1) apparently broken
2) logged wholesale

This means that the exports aren't set correctly, and that once they're fixed, your logs will contain the very same information that the entire purpose of this system is to keep out of logs

```
Setting environment variables from .travis.yml
$ export ABC_KEY={:secure=>
/home/travis/build.sh: eval: line 45: syntax error near unexpected token `newline'
/home/travis/build.sh: eval: line 45: `export ABC_KEY={:secure=>'
$ export 1a2b3c4d="} ABC_KEY={:secure=>"
```

Other than that I've replaced the real name of the environment variable with `ABC_KEY` and the real value of the key with `1a2b3c4d`, this is unedited.  Note that each (ruby hash?) is cut off after their (whatever ruby people call fat arrows.)

The censored key is the encrypted value, not the unencrypted value.

There are two such keys in my `.travis.yml`; only the first appears in the log.  However, using code, I've verified that neither are set in the environment.

Here is an NSA-certified `.travis.yml` for you:

https://gist.github.com/StoneCypher/a5e516889b95c324be5421e1f9a17ce3

The referenced `gulp` deploy steps work locally, but won't work in Travis land because they rely on the envvars for their AWS keys.

I am somewhat confused.  I believe this may be a Travis bug, but I'm open to the possibility that I screwed this up somehow.

![image](https://cloud.githubusercontent.com/assets/77482/16062416/e2ff017e-3247-11e6-9632-159e224afc89.png)

**Comment by solarce** [comment]
Hello @StoneCypher 

This repository's issue are only for the `worker` codebase. Please file your issue in https://github.com/travis-ci/travis-ci/issues/ for general help with Travis CI.
