### ISSUE TITLE
Not working package through apt addon

### ISSUE THREAD

**Issue by ale5000-git** [travis-ci/worker#198]
I'm not sure if it is the right place to report it but when I set android-tools-adb in the apt addon inside .travis.yml then I get "Unable to locate package android-tools-adb":

The package is whitelisted so I don't know what is the problem.

**Comment by meatballhat** [comment]
@ale5000-git This is definitely not the right place 😄   Can you open an issue over at https://github.com/travis-ci/travis-ci/issues ?

**Comment by ale5000-git** [comment]
Ok, [done](https://github.com/travis-ci/travis-ci/issues/6577).
Thanks.
