### ISSUE TITLE
Make the log output limit of 4mb configurable

### ISSUE THREAD

**Issue by joshk** [travis-ci/worker#208]
Hi Hi

Several Enterprise customers have asked to be able to customize the log output limit from 4mb to 40mb.

Can we please make this limit configurable so customers can choose their own limit.

Thanks a bundle

Josh

**Comment by joshk** [comment]
The PR looks great. What are the next steps to have this merged and a new worker version released for Enterprise customers to use?

**Comment by solarce** [comment]
@emdantrim is working on a new release for this @joshk @danishkhan.

**Comment by danishkhan** [comment]
I see that the PR was merged. What does the customer need to do on their worker to customize the log output limit?

**Comment by emdantrim** [comment]
Looks like setting `TRAVIS_WORKER_MAX_LOG_LENGTH` will do the trick.

```defaultMaxLogLength = 4500000```

The setting is measured in bytes, and 4,500,000 bytes is 4.5 MB. So, for 40MB, you'd do something like 40,000,000. 

```export TRAVIS_WORKER_MAX_LOG_LENGTH=40000000```

**Comment by abhibana** [comment]
It didn't work for me. The log length limit is still 4MB. :(

**Comment by AhirePawan** [comment]
Hi, where to write this line?
export TRAVIS_WORKER_MAX_LOG_LENGTH=40000000

**Comment by rghorpade-mdsol** [comment]
where to set export TRAVIS_WORKER_MAX_LOG_LENGTH=40000000
