### ISSUE TITLE
For file backend, allow changing default file permissions of created *.state and *.log files

### ISSUE THREAD

**Issue by singpolyma** [travis-ci/worker#212]
Right now, these files are always created with permissions 0600, but I would like to change this to 0660.

**Comment by meatballhat** [comment]
@singpolyma Sorry for the long delay.  It would help me if I understood more about your use case.  Are you able to provide more details?

**Comment by singpolyma** [comment]
Basically, I am communicating with the travis worker from a process running as a different user and so I would like the permissions to allow the group to read and remove so that my process can access the results, etc

**Comment by meatballhat** [comment]
@singpolyma Please holler if this is still important to you :heart:
