### ISSUE TITLE
Docker native mode doesn't seem to work with v2.50

### ISSUE THREAD

**Issue by sepiroth887** [travis-ci/worker#224]
Hi, 

I'm almost sure I'm doing something wrong. I have travis worker configured via env variables to run NATIVE docker mode which should avoid the ssh upload of build.sh. 

However while I can see the PRIVILEGED=true flag working, setting TRAVIS_WORKER_DOCKER_NATIVE=true will still launch a worker trying to use ssh. 

Any idea what I'm doing wrong?

**Comment by sepiroth887** [comment]
Doh. Ignore it. Somehow a 2.3 worker binary snuck in.. my bad.

**Comment by meatballhat** [comment]
Phew! :grin:
