### ISSUE TITLE
Ruby 2.3.3 doesn't work in non-travis environment

### ISSUE THREAD

**Issue by markelog** [travis-ci/worker#233]
Is rubies binaries on http://rubies.travis-ci.org/, supposed to work in non-travis environment?

Since 2.3.x and 2.4.x versions for OSX 10.12 (at least) do not work, showing me:
```bash
dyld: Library not loaded: /Users/travis/.rvm/rubies/ruby-2.3.2/lib/libruby.2.3.0.dylib
  Referenced from: <removed>
  Reason: image not found
```
Not sure if this issue belongs to this repo, so apologies if that the case

**Comment by markelog** [comment]
If working (from http://rubies.travis-ci.org/usage) with `rvm` –

```bash
$ rvm reinstall ruby-head --binary
...
ruby-head - #validate archive
ruby-head - #extract
ruby-head - #validate binary
Libraries missing for ruby-head: /Users/travis/.rvm/rubies/ruby-head/lib/libruby.2.4.0.dylib. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, stopping installation.
```

**Comment by markelog** [comment]
Same story with 2.1.x, different with 2.2.x - https://github.com/travis-ci/worker/issues/234

**Comment by BanzaiMan** [comment]
Same with #234. This is not the right repository.

Probably the same as https://github.com/travis-ci/travis-rubies/issues/26.
