### ISSUE TITLE
Incorrect ruby 2.2.6 on http://rubies.travis-ci.org/osx/10.12/x86_64/ruby-2.2.6

### ISSUE THREAD

**Issue by markelog** [travis-ci/worker#234]
That is compiled 2.2.2 version :/

**Comment by markelog** [comment]
Actually, it seems all 2.2.x osx rubies for mac 10.12 are 2.2.2

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue, but this is not the right repository. Please open it at https://github.com/travis-ci/travis-ci/issues. Thanks.

**Comment by BanzaiMan** [comment]
I think https://github.com/travis-ci/travis-rubies/issues/26 is the correct issue to track this.

**Comment by markelog** [comment]
> I think travis-ci/travis-rubies#26 is the correct issue to track this.

It doesn't look this way, since 2.2.x rubies work it's just the wrong version :), which seems to be different issue entierly

**Comment by BanzaiMan** [comment]
Very well. Please open a new issue on https://github.com/travis-ci/travis-ci/issues with more details. In particular, the build log URL which shows the problem. Thanks.

**Comment by markelog** [comment]
Oh, i wasn't downloading those rubies from travis environment, I installed it on my system, by downloading it from http://rubies.travis-ci.org/osx/10.12/x86_64/ruby-2.2.6 (or any other version 2.2.x version for mac) gives me with `ruby --version`: `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]`.

I opened issue on https://github.com/travis-ci/travis-rubies/issues/27, I hope that's okay

**Comment by BanzaiMan** [comment]
Unless you are pointing to the archive's `ruby`, I'm not sure if that output is reliable.
