### ISSUE TITLE
log timeout

### ISSUE THREAD

**Issue by singpolyma** [travis-ci/worker#244]
Just had my local install issue a log timeout... while I was tailing the log file and it clearly had content in it!  Does the log timeout not measure the same thing as what goes into the actual log file?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
The log timeout measures the job producing logs to stdout, which worker then delivers via amqp. If worker does not see any logs for extended periods of time, it cancels the job. Does that clarify?

**Comment by singpolyma** [comment]
So maybe the job was only outputting to stderr? And then that still goes to the job's log file, but doesn't count for timeout?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
stderr is also included in that calculation. When talking about the log file, are you using the `file_log_writer`?

**Comment by singpolyma** [comment]
Using `TRAVIS_WORKER_QUEUE_TYPE=file` and it makes a subfolder `log` with per-job logfiles. Travis worker version 2.5.0 rev=da3a432228dff

**Comment by meatballhat** [comment]
@singpolyma Please yell if this should be reopened :heart:
