### ISSUE TITLE
Limit docker disk space?

### ISSUE THREAD

**Issue by singpolyma** [travis-ci/worker#245]
Travis offers easy options to limit the CPUs and RAM used by docker containers -- but what about disk space?  Is there any easy way to limit that?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
You can provide any quotas via the `DOCKER_OPTS` environment variable. The exact settings depends on the storage driver. Here is an example for `devicemapper`: http://stackoverflow.com/a/24393016
