### ISSUE TITLE
Stream Output from travis_wait to Standard Output and Error

### ISSUE THREAD

**Issue by naftulikay** [travis-ci/worker#283]
Presently, it appears that the only workaround for long-running builds is to use `travis_wait N` where `N` is the number of minutes to allow a build to run for.

This command unfortunately does not stream its output to the user, so it is necessary to wait until a job has completely finished before knowing what went wrong. In large test cases or scripts that take 30 minutes to run, it would be nice to see test failures without having to wait the full 30 minutes.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This logic is implemented in https://github.com/travis-ci/travis-build /cc @BanzaiMan

**Comment by BanzaiMan** [comment]
Indeed, this issue  does not belong here. Please use https://github.com/travisciI/travis-ci to report this.

However, I should point out that the purpose of `travis_wait` is to keep the job alive when there is *no* output to `STDOUT`. If you have something written on `STDOUT` you want to read immediately, you should not use `travis_wait`.
