### ISSUE TITLE
Understanding travis-worker and installing it locally.

### ISSUE THREAD

**Issue by spurtichopra** [travis-ci/worker#284]
I am interested to know about travis-worker and other components connected to it.
Is there any specific document which can help me to setup and configure travis-worker and rest 
of the components (travis-build, travis-log, travis-hub) locally on a VM.

Also, I would appreciate if you can provide any documents or links which can help me understand the below better 
a) There are installation steps available for travis-worker in README.md, but how do we configure travis-build, travis-log and travis-hub with it ?
b) How could we run a sample job with travis-worker and docker as a backend ?
c) As per my understanding travis-worker is responsible for creating VM/container with configured backend (docker, gce,  etc. ) then in such a scenario what is the role of travis-cookbooks ?

**Update**: The action I would like to see based on this issue is improvements and additions to `README.md`, meaning that I consider this issue to be about documentation enhancement.

**Comment by chongzhe** [comment]
+1 would appreciate some more detailed documentation
