### ISSUE TITLE
travis docker version has a bug to support 'shared' flag

### ISSUE THREAD

**Issue by reachlin** [travis-ci/worker#329]
it seems the docker from travis can't support 'shared' flag for '-v' parameter: https://travis-ci.org/reachlin/k8s0/builds/250671863

i googled it, and seems some certain docker version has this problem, https://github.com/docker/libcontainer/pull/632
please upgrade your docker. thanks.

**Comment by meatballhat** [comment]
@reachlin Hello!  The repository you want for this issue is https://github.com/travis-ci/travis-ci/issues.  Thank you!
