### ISSUE TITLE
Docker build failure attempting to run sudo apt-get update

### ISSUE THREAD

**Issue by todkap** [travis-ci/worker#349]
Attempting to follow the documentation for enabling [docker builds] (https://enterprise.travis-ci.com/docker-builds) for may travis workers and see the following..

> Get:62 http://ppa.launchpad.net precise/main i386 Packages [3,133 B]
> Err http://ppa.launchpad.net precise/main amd64 Packages
>   404  Not Found
> Err http://ppa.launchpad.net precise/main i386 Packages
>   404  Not Found
> Fetched 62 B in 3s (16 B/s)
> W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found
> 
> W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> 
> 
> The command "sudo apt-get update" failed and exited with 100 during .
> 

**Complete logs here**
[travis_log.txt](https://github.com/travis-ci/worker/files/1174668/travis_log.txt)

**Comment by solarce** [comment]
@todkap this appears to be an _environment_ issue and isn't directly related to the `worker` code base. Could you please email enterprise@travis-ci.com so that our Enterprise Support team can assist you?

**Comment by solarce** [comment]
More specifically, there's a _runtime_ fix that `travis-build` does to fix the URL in the redis ppa name, https://github.com/travis-ci/travis-build/pull/958 and based on the log output, it seems like that fix isn't getting done,

```
Err http://ppa.launchpad.net precise/main amd64 Packages
  404  Not Found
Err http://ppa.launchpad.net precise/main i386 Packages
  404  Not Found
Fetched 62 B in 3s (16 B/s)
W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
```

Things related to the `travis-build` version that's available in your Enterprise installation are best handled by Enterprise support at this time. Thanks!

**Comment by todkap** [comment]
Contacted support team.
