### ISSUE TITLE
Automated builds on Docker Hub

### ISSUE THREAD

**Issue by soulshake** [travis-ci/worker#358]
In trying to determine where the Docker Hub [travisci/worker](https://hub.docker.com/r/travisci/worker/tags/) images come from, I was pointed [here](https://github.com/travis-ci/worker/blob/master/.travis.yml#L45-L46):

```
- if [[ $TRAVIS_PULL_REQUEST = 'false' && $DOCKER_LOGIN_PASSWORD && $DOCKER_LOGIN_USERNAME ]]; then
    make docker-build smoke-docker docker-push;
  fi
```

Would we consider using automated builds on Docker Hub to improve visibility of the image source and ensure the `Dockerfile` in the repo really corresponds to the images on the Hub? (The `Dockerfile` currently on master doesn't build at all for me locally; I think this would help with issues like #284.)

**Comment by meatballhat** [comment]
I am 👎 to strictly supporting automated Docker Hub builds.  The size of the alpine-based image is a big advantage, imho.  I think that adding another `Dockerfile` that is compatible with Docker Hub automated builds is fine, although I wonder who is going to use it 😄 🤔 ...

I don't think there needs to be a strict contract between the `Dockerfile` currently in this repository and the automated build process offered by Docker Hub.

In the specific case of #284, this is an area that I would like to address with documentation.

Please holler if you feel that I've incorrectly closed this issue! ❤️
