### ISSUE TITLE
File permissions just gone up to 664

### ISSUE THREAD

**Issue by szepeviktor** [travis-ci/worker#577]
Could it be that in v6.1.0 files right after git clone+git checkout have 664 permissions instead of 644?

Up to today it was 644.

See https://travis-ci.org/nunomaduro/larastan/jobs/470628881#L462

Thank you.

**Comment by meatballhat** [comment]
@szepeviktor Thank you for bringing this up. Given that the `git` operations are performed via a script generated by [travis-build](https://github.com/travis-ci/travis-build) and run on an image prepared via [packer-templates](https://github.com/travis-ci/packer-templates), I doubt that this project has much to do with it. Are you able to raise this issue via either the [community forum](https://travis-ci.community/) or by [contacting support](mailto:support@travis-ci.org)?

**Comment by szepeviktor** [comment]
Thank you.
