### ISSUE TITLE
Travis Worker 6.2.1 Allocates Only 1 CPU instead of 2

### ISSUE THREAD

**Issue by amarkpayne** [travis-ci/worker#604]
Below are parts of two logs for Travis builds of the same commit but on different versions of Travis Worker. Specifically, compare the number of CPUs available and the reduced memory available in 6.2.1.

6.2.0
```
Worker information
hostname: c490198c-6702-4f26-b1bc-83376558b612@1.production-1-worker-org-gce-b22j
version: v6.2.0 https://github.com/travis-ci/worker/tree/5e5476e01646095f48eec13196fdb3faf8f5cbf7
instance: travis-job-36dbf890-b3f6-4c78-aaa1-aa3873ef4fc8 travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)

...

$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1

...

$ free -m
             total       used       free     shared    buffers     cached
Mem:          7479       1181       6298        189         63        865
-/+ buffers/cache:        252       7227
Swap:            0          0          0
```

6.2.1
```
Worker information
hostname: e414c302-663a-4aec-bdc7-49b75aa60ea7@1.worker-org-79f7449b7b-cf75n.gce-production-1
version: v6.2.1 https://github.com/travis-ci/worker/tree/4e3246c044eb4915c2378ffacd0b3d3ed0136bba
instance: travis-job-e45f645a-bffb-45cd-8d34-8ffef77cc572 travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)

...

$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel

...

$ free -m
             total       used       free     shared    buffers     cached
Mem:          3699       1165       2534        189         63        864
-/+ buffers/cache:        237       3462
Swap:            0          0          0
```
 
 
 
 
With the reduced memory alloacted with only 1 CPU, our Travis builds are unable to complete. Is this a bug in Travis Worker or is the current plan to reduce the CPUs available for Travis builds?

**Comment by potiuk** [comment]
I would love to know it as well. It's hitting us big time and is against official specs of workers from Travis.

**Comment by cotsog** [comment]
Can you try to restart your failing builds and let us know if it happens again? Thanks!

**Comment by amarkpayne** [comment]
We have restarted them numerous times, but the 6.2.1 build consistently fail (this has happened to us at least 10 times in the past 24 hours). We have since added this additional logging to our builds with CPU and memory info and the 6.2.1 builds consistently show 1 CPU and half the expected memory.

**Comment by cotsog** [comment]
@amarkpayne we have reverted a change in production @ 2019-07-23 18:11 UTC that should fix this issue. Please restart your builds again and let me know if it's still happening. Thanks!

**Comment by amarkpayne** [comment]
Thanks for the very fast response @cotsog ! We are restarting our builds and will let you know as soon as we see a 6.2.1 build.

**Comment by amarkpayne** [comment]
@cotsog was the reverted change in production simply to fall back to 6.2.0 only? Our builds are passing, but we have not seen a 6.2.1 build since your change (we have seen 5-8 builds at this point). Given this, we can confirm that our builds pass again, but cannot say one way or another about the status of 6.2.1

**Comment by potiuk** [comment]
I confirm it works for us. Thanks @cotsog

**Comment by amarkpayne** [comment]
We finally got a 6.2.1 build again, and can confirm that the number of CPUs and memory are as they should be. Thanks again for your help with this @cotsog 

```
Worker information
hostname: be6c146c-d9bc-4a3c-8a07-6c57e0fb4731@1.worker-org-78c6f46d9c-mqq7g.gce-production-1
version: v6.2.1 https://github.com/travis-ci/worker/tree/4e3246c044eb4915c2378ffacd0b3d3ed0136bba
instance: travis-job-a2d5214e-ddd7-4217-92ee-12448df9bd5b travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)

...

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lscpu; fi
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel

...

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
             total       used       free     shared    buffers     cached
Mem:          7479       1190       6289        189         63        868
-/+ buffers/cache:        258       7221
Swap:            0          0          0
```

**Comment by Duologic** [comment]
@amarkpayne The change was caused by a configuration error, we are in the process of moving the workers to Kubernetes. We've updated the [configuration](https://github.com/travis-ci/kubernetes-config/commit/8430cbcc1c951b6ef19f6b06056333e4e0176712), 50% of our (Linux/Windows) workers are now running on Kubernetes, the other 50% will follow today. Thanks for the quick feedback!
